Repository SEP-Summer-Resit/Functional, pull requests merged in 2024-07, with the labels that each got.

#20 Built-in Command
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  README.md
  config/actions.xml
  config/entities.dot
  libs/com/alexmerz/graphviz/dot-parser/1.0/dot-parser-1.0.pom
  libs/com/alexmerz/graphviz/dot-parser/maven-metadata.xml
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/edu/uob/Artefacts.java
  src/main/java/edu/uob/Characters.java
  src/main/java/edu/uob/Furniture.java
  src/main/java/edu/uob/GameClient.java
  src/main/java/edu/uob/GameServer.java
  src/main/java/edu/uob/Locations.java
  src/main/java/edu/uob/Paths.java
  src/main/java/edu/uob/Players.java
  src/test/java/CommandTests.java
  target/classes/edu/uob/GameClient.class
  target/classes/edu/uob/GameServer.class
  target/classes/edu/uob/Players.class
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  target/surefire-reports/TEST-edu.uob.CommandTests.xml
  target/surefire-reports/edu.uob.CommandTests.txt
  target/test-classes/edu/uob/CommandTests.class
Labels: enhancement

#25 Renamed some classes to make more sense. Added an entities class and …
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/libraries/Maven__com_alexmerz_graphviz_dot_parser_1_0.xml
  .idea/libraries/Maven__org_apiguardian_apiguardian_api_1_1_2.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_5_8_2.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_api_5_8_2.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_engine_5_8_2.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_params_5_8_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_commons_1_8_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_engine_1_8_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_launcher_1_8_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_suite_1_8_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_suite_api_1_8_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_suite_commons_1_8_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_suite_engine_1_8_2.xml
  .idea/libraries/Maven__org_opentest4j_opentest4j_1_2_0.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  cw-stag.iml
  src/main/java/edu/uob/Artefact.java
  src/main/java/edu/uob/Character.java
  src/main/java/edu/uob/Entity.java
  src/main/java/edu/uob/Game.java
  src/main/java/edu/uob/Location.java
  src/main/java/edu/uob/Locations.java
  src/main/java/edu/uob/Path.java
  src/main/java/edu/uob/Players.java
Labels: bug

#46 Command handler
  .gitignore
  .idea/workspace.xml
  config/entities.dot
  src/main/java/edu/uob/Furniture.java
  src/main/java/edu/uob/GameClient.java
  src/main/java/edu/uob/GameServer.java
  src/main/java/edu/uob/Location.java
  src/main/java/edu/uob/Path.java
  src/test/java/CommandTests.java
  target/classes/edu/uob/Furniture.class
  target/classes/edu/uob/Game.class
  target/classes/edu/uob/GameClient.class
  target/classes/edu/uob/GameServer.class
  target/classes/edu/uob/Location.class
  target/classes/edu/uob/Path.class
  target/classes/edu/uob/Player.class
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  target/surefire-reports/TEST-edu.uob.CommandTests.xml
  target/surefire-reports/edu.uob.CommandTests.txt
  target/test-classes/edu/uob/CommandTests.class
Labels: enhancement

#38 updated github workflow
  .github/workflows/maven.yml
  .gitignore
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  .mvn/wrapper/maven-wrapper.properties
  README.md
  config/actions.xml
  config/entities.dot
  cw-stag.iml
  libs/com/alexmerz/graphviz/dot-parser/1.0/dot-parser-1.0.pom
  libs/com/alexmerz/graphviz/dot-parser/maven-metadata.xml
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/edu/uob/Artefact.java
  src/main/java/edu/uob/Character.java
  src/main/java/edu/uob/Entity.java
  src/main/java/edu/uob/Furniture.java
  src/main/java/edu/uob/GameClient.java
  src/main/java/edu/uob/GameServer.java
  src/main/java/edu/uob/Location.java
  src/main/java/edu/uob/Path.java
  src/main/java/edu/uob/Player.java
  src/test/java/CommandTests.java
  target/classes/edu/uob/Artefact.class
  target/classes/edu/uob/Character.class
  target/classes/edu/uob/Entity.class
  target/classes/edu/uob/Furniture.class
  target/classes/edu/uob/GameClient.class
  target/classes/edu/uob/GameServer.class
  target/classes/edu/uob/Location.class
  target/classes/edu/uob/Path.class
  target/classes/edu/uob/Player.class
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/test-classes/CommandTests.class
Labels: enhancement

#64 solve maven test CI fail problem
  .idea/workspace.xml
Labels: CI
